compiler:
	g++ -std=c++11 Game.cpp -o game -lpthread -O3 -g3

f5x5: 
	time ./game Puzzle5x5.txt
	
f6x6:
	time ./game Puzzle6x6.txt

f7x7:
	time ./game Puzzle7x7.txt

f8x8:
	time ./game Puzzle8x8.txt

